#Group H
#	Jesse Boswell
#	Craig Nafus
#	Christian Betancourt
#	Daniel Lee
#	Taylor DeLaughter
#	Satvir Singh
#	Ameera Fatima
#	Nancy Joy
#CSCE 2110.001
#11/5/15

start: GroupH_10_P4_Main.cpp  GroupH_10_P4_Functions.cpp GroupH_10_P4_Header.h
	g++ GroupH_10_P4_Main.cpp  GroupH_10_P4_Functions.cpp -o prog4 
  
run: prog4
	./prog4